### ISSUE TITLE
DisplayMan --show-config prints Could not find file 'C:\WINDOWS\system32\--show-config'.

### ISSUE THREAD

**Issue by nhamer** [mastersign/Mastersign.DisplayManager#1]
showConfig doesn't set  recognizedValidOption = true;

https://github.com/mastersign/Mastersign.DisplayManager/blob/28c4c4a8efe47dff4d45053ddb01a67f72a189b8/Mastersign.DisplayManager/ArgumentParser.cs#L51

**Comment by mastersign** [comment]
Thanks!
